### ISSUE TITLE
Help.py Docstring on Class

### ISSUE THREAD

**Issue by runew0lf** [SirThane/SESTREN#4]
Good morning sir!

The helpfile shows in the description says that docstring on class sets the category, however, this is not the case?
        def category(tup):
            # Turn get cog (Category) name from cog/list tuples
            cog = tup[1].cog_name
            return '**__{0}:__**'.format(cog) if cog is not None else '**__\u200bNo Category:__**'

this is the function, however, it just displays the default cog name (class)

**Comment by SirThane** [comment]
If memory serves me correctly, d.py interprets the Class name as the name of the cog. I don't know if this behavior has changed due to an update in d.py. I have not touched my bot work in around 8 months. My time is currently being invested elsewhere and I don't believe I'll be back to Discord bot work for a bit longer.

As far as I can currently see, it is functioning as intended when it was written.
![image](https://user-images.githubusercontent.com/15083169/37869051-164c7cda-2f87-11e8-841b-fa8c486fb6d8.png)

**Comment by SirThane** [comment]
I think I may see the confusion. My language in the description seems to imply that a docstr on the cog Class becomes the cog name. This is not the case. The Class name becomes the cog name and the Class docstr becomes the cog description. This was the same functionality made in the logic of the d.py built-in help formatter that I used to write the cog.

![image](https://user-images.githubusercontent.com/15083169/37869078-a86c0f72-2f87-11e8-9c8b-bcc4b3888092.png)

![image](https://user-images.githubusercontent.com/15083169/37869081-b942f25c-2f87-11e8-9e4e-761bd1e326a3.png)

**Comment by SirThane** [comment]
I will change the description to reflect this so there will hopefully be no confusion.

Otherwise, does it work well?
